spring:
  profiles:
    active:
      - prod
      - cat
      - EN
  data:
    username: crazy_pro
    password: DBPass
    jdbcUrl: anyUrlToDB

---

spring:
  profiles: prod
  data:
    username: prod
    password: prodDBPass
    jdbcUrl: prodUrlToDB
